#ifndef __TERREATE_AUDIO_ALDEFS_HPP__
#define __TERREATE_AUDIO_ALDEFS_HPP__

#include <audio/ALhelper.hpp>

namespace Terreate::Audio {

enum class ALError {
  NO_ERR = AL_NO_ERROR,
  INVALID_NAME = AL_INVALID_NAME,
  INVALID_ENUM = AL_INVALID_ENUM,
  INVALID_VALUE = AL_INVALID_VALUE,
  INVALID_OPERATION = AL_INVALID_OPERATION,
  OUT_OF_MEMORY = AL_OUT_OF_MEMORY
};

enum class BufferFormat {
  MONO8 = AL_FORMAT_MONO8,
  MONO16 = AL_FORMAT_MONO16,
  STEREO8 = AL_FORMAT_STEREO8,
  STEREO16 = AL_FORMAT_STEREO16
};

enum class BufferProperty {
  FREQUENCY = AL_FREQUENCY,
  BITS = AL_BITS,
  CHANNELS = AL_CHANNELS,
  SIZE = AL_SIZE
};

enum class DistanceModel {
  NONE = AL_NONE,
  INVERSE = AL_INVERSE_DISTANCE,
  INVERSE_CLAMPED = AL_INVERSE_DISTANCE_CLAMPED,
  LINEAR = AL_LINEAR_DISTANCE,
  LINEAR_CLAMPED = AL_LINEAR_DISTANCE_CLAMPED,
  EXPONENTIAL = AL_EXPONENT_DISTANCE,
  EXPONENTIAL_CLAMPED = AL_EXPONENT_DISTANCE_CLAMPED
};

enum class SourceProperty {
  PITCH = AL_PITCH,
  GAIN = AL_GAIN,
  MIN_GAIN = AL_MIN_GAIN,
  MAX_GAIN = AL_MAX_GAIN,
  MAX_DISTANCE = AL_MAX_DISTANCE,
  ROLLOFF_FACTOR = AL_ROLLOFF_FACTOR,
  REFERENCE_DISTANCE = AL_REFERENCE_DISTANCE,
  CONE_INNER_ANGLE = AL_CONE_INNER_ANGLE,
  CONE_OUTER_ANGLE = AL_CONE_OUTER_ANGLE,
  CONE_OUTER_GAIN = AL_CONE_OUTER_GAIN,
  POSITION = AL_POSITION,
  VELOCITY = AL_VELOCITY,
  DIRECTION = AL_DIRECTION,
  SOURCE_RELATIVE = AL_SOURCE_RELATIVE,
  LOOPING = AL_LOOPING,
  BUFFER = AL_BUFFER,
  SOURCE_STATE = AL_SOURCE_STATE,
  BYTE_OFFSET = AL_BYTE_OFFSET,
  SAMPLE_OFFSET = AL_SAMPLE_OFFSET,
  SEC_OFFSET = AL_SEC_OFFSET,
  BUFFER_QUEUED = AL_BUFFERS_QUEUED,
  BUFFER_PROCESSED = AL_BUFFERS_PROCESSED
};

enum class SourceState {
  INITIAL = AL_INITIAL,
  PLAYING = AL_PLAYING,
  PAUSED = AL_PAUSED,
  STOPPED = AL_STOPPED
};

enum class SourceType {
  STATIC = AL_STATIC,
  STREAMING = AL_STREAMING,
  UNDETERMINED = AL_UNDETERMINED
};

} // namespace Terreate::Audio

#endif // __TERREATE_AUDIO_ALDEFS_HPP__
